-- AlterTable
ALTER TABLE "Customer" ALTER COLUMN "phone" DROP NOT NULL,
ALTER COLUMN "address" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Order" ALTER COLUMN "orderDate" SET DEFAULT CURRENT_TIMESTAMP;
